package altitude.source.code;

import java.util.HashMap;

import org.bukkit.entity.Player;

public class Objectives {
	
	public static HashMap<Player,Integer> completedobj = new HashMap<Player,Integer>();//objective that player completed, number
	public static HashMap<Integer,String> objectives = new HashMap<Integer,String>();//objective by number
	
	public void add(){
		objectives.put(1, "Shoot Maurice");
		objectives.put(2, "Examine Maurice's phone for information");
		objectives.put(3, "Leave the locker room when ready");
		objectives.put(4, "Sneak past the police");
		objectives.put(5, "Hack the camera");
		objectives.put(6, "Follow the data flow line to its source");
		objectives.put(7, "Unlock the door");
		objectives.put(8, "Reach the upper level");
		objectives.put(9, "Throw lure to the designated area");
		objectives.put(10, "Use the lure to distract the cop");
		objectives.put(11, "Find and hack the guard with the access code");
		objectives.put(12, "Hack into the stadium's network");
		objectives.put(13, "Create a blackout");
		objectives.put(14, "Escape the stadium");
		objectives.put(15, "Escape the stadium");
		objectives.put(16, "Reach your hideout");
		objectives.put(17, "Go to sleep");
		objectives.put(18, "Exit your motel room");
		objectives.put(19, "Profile people for potential crimes near your hideout");
		objectives.put(20, "Investigate the potential crime area");
		objectives.put(21, "Watch for criminal behaviour");
		objectives.put(22, "Join the party in the backyard");
		objectives.put(23, "Head inside Nicky's home");
		objectives.put(24, "Listen in on Nicky's phone");
		objectives.put(25, "Take down the suspect");
		objectives.put(26, "Hack the caller's phone for answers");
		objectives.put(27, "Purchase the 416 assault rifle");
		objectives.put(28, "Locate a guard with the access code");
		objectives.put(29, "Hack the guard with the access code");
		objectives.put(30, "Use access code to reach the sewers");
		objectives.put(31, "Leave the area");
		objectives.put(32, "Find 2XTheTap");
		objectives.put(33, "Kill 2XTheTap before he evades");
		objectives.put(34, "Access the online contracts");
		objectives.put(35, "Reach the West Island for the driving contract");
		objectives.put(36, "Reach the fugitive undetected");
		objectives.put(37, "Escape the lockdown area undetected");
		objectives.put(38, "Deliver the fugitive and avoid all detection");
		objectives.put(39, "Meet with Badboy17");
		objectives.put(40, "Reach the ctOS Executive Offices");
		objectives.put(41, "Enter through the underground loading zone");
		objectives.put(42, "Locate a guard with the access code");
		objectives.put(43, "Hack the access point to breach the unsecured laptop");
		objectives.put(44, "Hack the laptop to upload a virus and give Clara access");
		objectives.put(45, "Escape the plaza");
		objectives.put(46, "Escape the Police scan undetected");
		objectives.put(47, "Reach the mystery caller's signal source");
		objectives.put(48, "Pinpoint the signal's location");
		objectives.put(49, "Find and activate the ctOS boxes");
		objectives.put(50, "Access the building network to reach the signal source.");
		objectives.put(51, "Investigate the apartment");
		objectives.put(52, "Hack the phone");
		objectives.put(53, "Kill all fixers or escape");
		objectives.put(54, "Follow the traced call to Damien");
		objectives.put(55, "Climb to meet Jordi on the patio deck");
		objectives.put(56, "Infiltrate the railyard");
		objectives.put(57, "Interrogate the Fixer Boss");
		objectives.put(58, "Use the Profiler to find Angelo Tucci's niece");
		objectives.put(59, "Hack the niece's phone");
		objectives.put(60, "Hack the niece's phone (again)");
		objectives.put(61, "Kill Angelo Tucci before he reaches the prison");
		objectives.put(62, "Eliminate Angelo Tucci before he escapes");
		objectives.put(63, "Kill Angelo's allies or escape");
		objectives.put(64, "Escape your cell");
		objectives.put(65, "Locate the survivor");
		objectives.put(66, "Access the network to view the exercise yard");
		objectives.put(67, "Find the stadium survivor: Raul Lionzo");
		objectives.put(68, "Get to the survivor in the basement");
		objectives.put(69, "Take out the corrupt guards");
		objectives.put(70, "Confront the survivor");
		objectives.put(71, "Exit the prison");
		objectives.put(72, "Escape the Police");
		objectives.put(73, "Meet Damien at the plaza");
		objectives.put(74, "Reach Nicky's house");
		objectives.put(75, "Get to the train station where Jackson is located");
		objectives.put(76, "Hack the train undetected to get Jackson away safely");
		objectives.put(77, "Take down the Fixers before they reach Jackson");
		objectives.put(78, "Eliminate the remaining Fixers");
		objectives.put(79, "Board the L-Train and find Jackson");
		objectives.put(80, "Buy some crafting components");
		objectives.put(81, "Locate a guard with the access code");
		objectives.put(82, "Download the access code");
		objectives.put(83, "Find the access code to Racine's office");
		objectives.put(84, "Search Racine's office for clues on Nicky");
		objectives.put(85, "Hack Racine's phone");
		objectives.put(86, "Take down the target");
		objectives.put(87, "Defend Clara from the attackers");
		objectives.put(88, "Escort Clara to her car");
		objectives.put(89, "Escape the motel area");
		objectives.put(90, "Search for bridge access");
		objectives.put(91, "Follow Clara");
		objectives.put(92, "Profile the homeless for clues");
		objectives.put(93, "Hack the caller");
		objectives.put(94, "Kill the Fixer before he reaches Tobias");
		objectives.put(95, "Kill the Fixer's backup or escape");
		objectives.put(96, "Reach the poker game");
		objectives.put(97, "Join the game and draw out Tobias");
		objectives.put(98, "Catch Tobias. Do not kill him");
		objectives.put(99, "Reach the bunker island");
		objectives.put(100, "Power up the generators to restore the bunker");
		objectives.put(101, "Enter the bunker");
		objectives.put(102, "Search for the power controls");
		objectives.put(103, "Power up the bunker");
		objectives.put(104, "Locate a guard with the access code");
		objectives.put(105, "Download access code");
		objectives.put(106, "Hack the ctOS server");
		objectives.put(107, "Kill all the ctOS guards or escape the area");
		objectives.put(108, "Disable all three security terminals");
		objectives.put(109, "The gate is open, unlock the ctOS Tower");
		objectives.put(110, "Leave the area");
		objectives.put(111, "Connect remotely to Rossi-Fremont");
		objectives.put(112, "Track the source of Damien's IP address");
		objectives.put(113, "Find access to Bedbug's home");
		objectives.put(114, "Install tracker on Bedbug's phone");
		objectives.put(115, "Follow Bedbug to get blackmail. Remain unseen.");
		objectives.put(116, "Use cameras to follow Bedbug");
		objectives.put(117, "Help Rabbit escape");
		objectives.put(118, "Call Rabbit");
		objectives.put(119, "Guide Rabbit safely through the Viceroys");
		objectives.put(120, "Leave the area");
		objectives.put(121, "Reach the Sienna Brick Factory");
		objectives.put(122, "Find security footage to plan your attack");
		objectives.put(123, "Prepare an ambush against the Viceroy hitmen");
		objectives.put(124, "Viceroys incoming. Find a good vantage point");
		objectives.put(125, "Eliminate all of Iraq's crew");
		objectives.put(126, "Hack the phone to intercept the call");
		objectives.put(127, "Take down the fleeing Viceroy");
		objectives.put(128, "Reach Bedbug's location");
		objectives.put(129, "Follow Bedbug undetected");
		objectives.put(130, "Call Bedbug");
		objectives.put(131, "Hack the terminal to display Bedbug's terminal");
		objectives.put(132, "Track the auction briefcase and watch for hand-offs");
		objectives.put(133, "Follow the briefcase unseen");
		objectives.put(134, "Tail the boat carrying the briefcase");
		objectives.put(135, "Locate the briefcase unseen");
		objectives.put(136, "Infiltrate the marina to get the briefcase");
		objectives.put(137, "Escape the marina");
		objectives.put(138, "Locate a guard with the access code");
		objectives.put(139, "Download access code");
		objectives.put(140, "Hack the ctOS server");
		objectives.put(141, "Leave the area");
		objectives.put(142, "Hack the ctOS box to find Crispin");
		objectives.put(143, "Eliminate Crispin");
		objectives.put(144, "Hack Crispin's phone to obtain data");
		objectives.put(145, "Go to the private lounge, Infinite 92");
		objectives.put(146, "Follow the host");
		objectives.put(147, "Leave Infinite 92");
		objectives.put(148, "Follow the guide");
		objectives.put(149, "Follow the guide (again)");
		objectives.put(150, "Locate Iraq");
		objectives.put(151, "Scan Iraq's ID tags");
		objectives.put(152, "Eliminate all enemies");
		objectives.put(153, "Defend against reinforcements");
		objectives.put(154, "Find Jackson");
		objectives.put(155, "Get into position and contact Bedbug");
		objectives.put(156, "Escape the Viceroys");
		objectives.put(157, "Enter the bunker");
		objectives.put(158, "Reach the location of Kenny's last signal");
		objectives.put(159, "Eliminate all Fixers");
		objectives.put(160, "Start the data upload");
		objectives.put(161, "Defend the area until the upload is complete");
		objectives.put(162, "Eliminate all the Fixers");
		objectives.put(163, "Wipe the hard drive");
		objectives.put(164, "Chase down and eliminate the Fixer");
		objectives.put(165, "Locate a guard with the access code");
		objectives.put(166, "Hack the ctOS server");
		objectives.put(167, "Leave the area");
		objectives.put(168, "Locate a guard with the access code");
		objectives.put(169, "Use the Profiler to find the reset code");
		objectives.put(170, "Enter the new password in the marina computer");
		objectives.put(171, "Infiltrate the ctOS tower");
		objectives.put(172, "Activate the station to access data");
		objectives.put(173, "Look for Ray Kenney at Jed's bar");
		objectives.put(174, "Follow T-Bone");
		objectives.put(175, "Activate T-Bone's trap");
		objectives.put(176, "Follow T-Bone (again)");
		objectives.put(177, "Steal back T-Bone's truck");
		objectives.put(178, "Drop off the truck");
		objectives.put(179, "Kill all militia members or escape");
		objectives.put(180, "Tail the helicopter");
		objectives.put(181, "Hack the chopper to find 2 security chiefs. Stay undetected");
		objectives.put(182, "Take down both Blume security chiefs");
		objectives.put(183, "Kill all militia members or escape");
		objectives.put(184, "Take out the convoy before it reaches Blume");
		objectives.put(185, "Reach Blume");
		objectives.put(186, "Infiltrate Blume unseen");
		objectives.put(187, "Profile the ctOS box");
		objectives.put(188, "Find and activate the ctOS boxes");
		objectives.put(189, "Break into Blume's network unseen");
		objectives.put(190, "Install T-Bone's spyware");
		objectives.put(191, "Locate Damien's meeting");
		objectives.put(192, "Exit Blume");
		objectives.put(193, "Hurry to T-Bone's junkyard");
		objectives.put(194, "Eliminate the militia");
		objectives.put(195, "Regroup with T-Bone");
		objectives.put(196, "Follow and defend T-Bone");
		objectives.put(197, "Defend T-Bone");
		objectives.put(198, "Eliminate the militia to help T-Bone escape");
		objectives.put(199, "Follow T-Bone to the boat");
		objectives.put(200, "Escape Pawnee with T-Bone");
		objectives.put(201, "Enter Rossi-Fremont");
		objectives.put(202, "Reach Iraq's server room");
		objectives.put(203, "Download all server data");
		objectives.put(204, "Leave the Rossi-Fremont");
		objectives.put(205, "Follow Iraq");
		objectives.put(206, "Take down Iraq");
		objectives.put(207, "Eliminate Iraq's personal guards");
		objectives.put(208, "Leave Rossi-Fremont (again)");
		objectives.put(209, "Enter the bunker to analyse Iraq's data");
		objectives.put(210, "Trace the hacker");
		objectives.put(211, "Take out the Fixer");
		objectives.put(212, "Escape the Police");
		objectives.put(213, "Use the Profiler to find an access point");
		objectives.put(214, "Connect to T-Bone");
		objectives.put(215, "Lead T-Bone to safety");
		objectives.put(216, "Kill all the Fixers or escape");
		objectives.put(217, "Enter the Ambrose Theater discretely");
		objectives.put(218, "Profile guests to get to Defalt");
		objectives.put(219, "Hack Defalt's server");
		objectives.put(220, "Hack the network to find Nicky");
		objectives.put(221, "Take out Nicky's guard");
		objectives.put(222, "Hack the guard's phone");
		objectives.put(223, "Guide Nicky to a car");
		objectives.put(224, "Kill all Fixers or escape");
		objectives.put(225, "Leave town. Avoid the police");
		objectives.put(226, "Reach the Merlaut Hotel");
		objectives.put(227, "Eavesdrop on Quinn's party and find him");
		objectives.put(228, "Follow Quinn and the Mayor");
		objectives.put(229, "Access hotel's network and disable security");
		objectives.put(230, "Infiltrate the hotel");
		objectives.put(231, "Reach Quinn's office");
		objectives.put(232, "Fight your way across the rooftop");
		objectives.put(233, "Find Quinn");
		objectives.put(234, "Profile Lucky Quinn");
		objectives.put(235, "Download the video");
		objectives.put(236, "Escape the hotel");
		objectives.put(237, "Escape the police");
		objectives.put(238, "Race to save Clara");
		objectives.put(239, "Eliminate the hitmen");
		objectives.put(240, "Reach Clara");
		objectives.put(241, "Reach the bunker");
		objectives.put(242, "Locate Damien");
		objectives.put(243, "Gain entry into the central ctOS building");
		objectives.put(244, "Upload T-Bone's virus into the ctOS");
		objectives.put(245, "Shut down ctOS");
		objectives.put(246, "Use a boat to reach Damien");
		objectives.put(247, "Find Damien");
		objectives.put(248, "Walk away or shoot Maurice");
	}
	
	public void setObjectiveCompleted(Player p){//sets the current objective completed
		int i = completedobj.get(p);
		i++;
		completedobj.put(p, i);
	}
	public String getCurrentObjective(Player p){ //gets objective that player is on, but hasnt comleted
		add();
		int i = completedobj.get(p);
		i++;
		return objectives.get(i);
		
	}
	public String getLastCompletedObjective(Player p){ //gets objective that player completed
		add();
		return objectives.get(completedobj.get(p));
	}
	public Integer getLastCompletedObjectiveNumber(Player p){
		add();
		return completedobj.get(p);
	}
	public Integer getCurrentObjectiveNumber(Player p){
		add();
		int i = completedobj.get(p);
		i++;
		return i;
		
	}
}
